- name: Get the splunk server
  ansible.builtin.include_tasks:
    file: get_splunk_server.yml
  when: ludus_splunk_server == ""

- name: Download Splunk UF from Splunk website
  win_shell: |
    wget -O "c:\splunkuf.msi" "https://download.splunk.com/products/universalforwarder/releases/9.4.0/windows/splunkforwarder-9.4.0-6b4ebe426ca6-windows-x64.msi"
- name: Install Splunk_UF MSI
  win_package:
    path: C:\splunkuf.msi
    arguments: 'RECEIVING_INDEXER=10.2.10.69:9997 SPLUNKUSERNAME=admin SPLUNKPASSWORD=zmalqp10 WINEVENTLOG_SEC_ENABLE=1 WINEVENTLOG_SYS_ENABLE=1 WINEVENTLOG_APP_ENABLE=1 PRIVILEGESECURITY=1 USE_LOCAL_SYSTEM=1 AGREETOLICENSE=YES /quiet'

- name: Start Splunk
  win_service:
    name: SplunkForwarder
    state: started
