- name: Get the splunk server
  ansible.builtin.include_tasks:
    file: get_splunk_server.yml
  when: ludus_splunk_server == ""

- name: Check if Splunk UF is installed
  win_stat:
    path: "C:\\Program Files\\SplunkUniversalForwarder\\bin\\splunk.exe"
  register: splunk_installed

- name: Stop Splunk UF if installed
  win_shell: |
    & "C:\\Program Files\\SplunkUniversalForwarder\\bin\\splunk.exe" stop
  when: splunk_installed.stat.exists
  ignore_errors: yes  # Ignore errors if Splunk is already stopped

- name: Uninstall Splunk UF
  win_shell: |
    msiexec /x "C:\\splunkuf.msi" /quiet /norestart
  when: splunk_installed.stat.exists

- name: Download Splunk UF from Splunk website
  win_shell: |
    wget -O "C:\\splunkuf.msi" "{{ splunk_package_url_uf }}"

- name: Install Splunk UF MSI
  win_package:
    path: C:\splunkuf.msi
    arguments: 'RECEIVING_INDEXER={{ ludus_splunk_server }} SPLUNKUSERNAME=admin SPLUNKPASSWORD=zmalqp10 WINEVENTLOG_SEC_ENABLE=1 WINEVENTLOG_SYS_ENABLE=1 WINEVENTLOG_APP_ENABLE=1 PRIVILEGESECURITY=1 USE_LOCAL_SYSTEM=1 AGREETOLICENSE=YES /quiet'

- name: Start Splunk UF Service
  win_service:
    name: SplunkForwarder
    state: started

