- name: Get the splunk server
  ansible.builtin.include_tasks:
    file: get_splunk_server.yml
  when: ludus_splunk_server == ""

- name: Download Splunk UF from Splunk website
  win_shell: |
    [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"
    (New-Object System.Net.WebClient).DownloadFile("{{ splunk_package_url_uf }}", "C:\splunkuf.msi")

- name: Install Splunk_UF MSI
  win_package:
    path: C:\splunkuf.msi
    arguments: 'RECEIVING_INDEXER={{ ludus_splunk_server }}:{{ ludus_splunk_server_forwarder_port }} SPLUNKUSERNAME=admin SPLUNKPASSWORD=zmalqp10 WINEVENTLOG_SEC_ENABLE=0 WINEVENTLOG_SYS_ENABLE=0 WINEVENTLOG_APP_ENABLE=0 PRIVILEGESECURITY=1 USE_LOCAL_SYSTEM=1 SPLUNKPASSWORD=Pl3ase-k1Ll-me:p AGREETOLICENSE=YES /quiet'

- name: Start Splunk
  win_service:
    name: SplunkForwarder
    state: started